apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-rec
  namespace: rec-img-prd
  labels:
    app: patrimonial-system
    env: prd
    type: recordings
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.24.53.126
    path: "/mnt/nfs/rec"
  storageClassName: storageclass-recordings
